# Captcha
#
# For support consider joining my discord: https://discord.gg/zgKr2YM

captcha-settings:
  attempts: 3
  color: false
  lines: true
  maps: 1000
  op-override: false
  permission-override: false
  time: 600