# Captcha
#
# For support consider joining my discord: https://discord.gg/zgKr2YM

captcha-settings:
  after: 7200000 # Require a captcha after 2 hours after the last completed Captcha (Only applies when mode is equal to AFTER)
  attempts: 3
  color: false
  lines: true
  maps: 1000
  mode: FIRSTJOIN # FIRSTJOIN, ALL, AFTER, RESTART, NONE
  op-override: false
  permission-override: false
  reverse: false # Reverse the answer, you may want to edit the join message accordingly
  require-move-action: true # Block chat messages when the player hasn't moved yet
  time: 600
  update-message: true