# Captcha
#
# For support consider joining my discord: https://discord.gg/zgKr2YM

captcha-settings:
  attempts: 3
  color: false
  lines: true
  maps: 1000
  mode: FIRSTJOIN # FIRSTJOIN, ALL, AFTER, RESTART, NONE
  after: 7200000 # Require a captcha after 2 hours after the last completed Captcha (Only applies when mode is equal to AFTER)
  op-override: false
  permission-override: false
  time: 600
  update-message: true