name: Captcha
version: 1.02
description: Bots are now the past
main: me.kyllian.captcha.CaptchaPlugin
api-version: 1.15

commands:
  captcha:
    usage: /<command>
    description: Main command of the Captcha plugin